#pragma once


#define __GET_FROM_INDEX__ITERATION_0(first, ...) first
#define __GET_FROM_INDEX__ITERATION_1(first, ...) __GET_FROM_INDEX__ITERATION_0(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_2(first, ...) __GET_FROM_INDEX__ITERATION_1(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_3(first, ...) __GET_FROM_INDEX__ITERATION_2(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_4(first, ...) __GET_FROM_INDEX__ITERATION_3(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_5(first, ...) __GET_FROM_INDEX__ITERATION_4(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_6(first, ...) __GET_FROM_INDEX__ITERATION_5(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_7(first, ...) __GET_FROM_INDEX__ITERATION_6(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_8(first, ...) __GET_FROM_INDEX__ITERATION_7(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_9(first, ...) __GET_FROM_INDEX__ITERATION_8(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_10(first, ...) __GET_FROM_INDEX__ITERATION_9(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_11(first, ...) __GET_FROM_INDEX__ITERATION_10(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_12(first, ...) __GET_FROM_INDEX__ITERATION_11(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_13(first, ...) __GET_FROM_INDEX__ITERATION_12(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_14(first, ...) __GET_FROM_INDEX__ITERATION_13(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_15(first, ...) __GET_FROM_INDEX__ITERATION_14(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_N_NOEXPAND(index, ...) __GET_FROM_INDEX__ITERATION_##index(__VA_ARGS__)
#define __GET_FROM_INDEX__ITERATION_N(index, ...) __GET_FROM_INDEX__ITERATION_N_NOEXPAND(index, __VA_ARGS__)
#define GET_FROM_INDEX(index, ...) __GET_FROM_INDEX__ITERATION_N(index, __VA_ARGS__)
