#pragma once

#include <helpers/ForEachMacro.h>
#include <helpers/GetFromIndexMacro.h>


#define __INTERTWINE_PACKS__UNPACK__IMPL__PACK(...) __VA_ARGS__
#define __INTERTWINE_PACKS__UNPACK_NOEXPAND(x) __INTERTWINE_PACKS__UNPACK__IMPL__##x
#define __INTERTWINE_PACKS__UNPACK(x, ...) __INTERTWINE_PACKS__UNPACK_NOEXPAND(x)


#define __INTERTWINE_PACKS12__GET_ELEMENT(pack, index) GET_FROM_INDEX(index, __INTERTWINE_PACKS__UNPACK(pack))
#define __INTERTWINE_PACKS12__ITERATION(index, firstPack, ...) PACK(FOR_EACH(__INTERTWINE_PACKS12__GET_ELEMENT, FORWARD(index), firstPack, __VA_ARGS__))
#define INTERTWINE_PACKS12(firstPack, ...) FOR_EACH2(__INTERTWINE_PACKS12__ITERATION, FORWARD(firstPack, __VA_ARGS__), RANGE(NARG(__INTERTWINE_PACKS__UNPACK(firstPack))))


#define __INTERTWINE_PACKS23__GET_ELEMENT(pack, index) GET_FROM_INDEX(index, __INTERTWINE_PACKS__UNPACK(pack))
#define __INTERTWINE_PACKS23__ITERATION(index, firstPack, ...) PACK(FOR_EACH2(__INTERTWINE_PACKS23__GET_ELEMENT, FORWARD(index), firstPack, __VA_ARGS__))
#define INTERTWINE_PACKS23(firstPack, ...) FOR_EACH3(__INTERTWINE_PACKS23__ITERATION, FORWARD(firstPack, __VA_ARGS__), RANGE(NARG(__INTERTWINE_PACKS__UNPACK(firstPack))))


#define __INTERTWINE_PACKS34__GET_ELEMENT(pack, index) GET_FROM_INDEX(index, __INTERTWINE_PACKS__UNPACK(pack))
#define __INTERTWINE_PACKS34__ITERATION(index, firstPack, ...) PACK(FOR_EACH3(__INTERTWINE_PACKS34__GET_ELEMENT, FORWARD(index), firstPack, __VA_ARGS__))
#define INTERTWINE_PACKS34(firstPack, ...) FOR_EACH4(__INTERTWINE_PACKS34__ITERATION, FORWARD(firstPack, __VA_ARGS__), RANGE(NARG(__INTERTWINE_PACKS__UNPACK(firstPack))))


#define __INTERTWINE_PACKS45__GET_ELEMENT(pack, index) GET_FROM_INDEX(index, __INTERTWINE_PACKS__UNPACK(pack))
#define __INTERTWINE_PACKS45__ITERATION(index, firstPack, ...) PACK(FOR_EACH4(__INTERTWINE_PACKS45__GET_ELEMENT, FORWARD(index), firstPack, __VA_ARGS__))
#define INTERTWINE_PACKS45(firstPack, ...) FOR_EACH5(__INTERTWINE_PACKS45__ITERATION, FORWARD(firstPack, __VA_ARGS__), RANGE(NARG(__INTERTWINE_PACKS__UNPACK(firstPack))))


#define __INTERTWINE_PACKS56__GET_ELEMENT(pack, index) GET_FROM_INDEX(index, __INTERTWINE_PACKS__UNPACK(pack))
#define __INTERTWINE_PACKS56__ITERATION(index, firstPack, ...) PACK(FOR_EACH5(__INTERTWINE_PACKS56__GET_ELEMENT, FORWARD(index), firstPack, __VA_ARGS__))
#define INTERTWINE_PACKS56(firstPack, ...) FOR_EACH6(__INTERTWINE_PACKS56__ITERATION, FORWARD(firstPack, __VA_ARGS__), RANGE(NARG(__INTERTWINE_PACKS__UNPACK(firstPack))))


#define __INTERTWINE_PACKS67__GET_ELEMENT(pack, index) GET_FROM_INDEX(index, __INTERTWINE_PACKS__UNPACK(pack))
#define __INTERTWINE_PACKS67__ITERATION(index, firstPack, ...) PACK(FOR_EACH6(__INTERTWINE_PACKS67__GET_ELEMENT, FORWARD(index), firstPack, __VA_ARGS__))
#define INTERTWINE_PACKS67(firstPack, ...) FOR_EACH7(__INTERTWINE_PACKS67__ITERATION, FORWARD(firstPack, __VA_ARGS__), RANGE(NARG(__INTERTWINE_PACKS__UNPACK(firstPack))))


#define __INTERTWINE_PACKS78__GET_ELEMENT(pack, index) GET_FROM_INDEX(index, __INTERTWINE_PACKS__UNPACK(pack))
#define __INTERTWINE_PACKS78__ITERATION(index, firstPack, ...) PACK(FOR_EACH7(__INTERTWINE_PACKS78__GET_ELEMENT, FORWARD(index), firstPack, __VA_ARGS__))
#define INTERTWINE_PACKS78(firstPack, ...) FOR_EACH8(__INTERTWINE_PACKS78__ITERATION, FORWARD(firstPack, __VA_ARGS__), RANGE(NARG(__INTERTWINE_PACKS__UNPACK(firstPack))))
