#pragma once


#define __RANGE__ITERATION_1 0
#define __RANGE__ITERATION_2 __RANGE__ITERATION_1, 1
#define __RANGE__ITERATION_3 __RANGE__ITERATION_2, 2
#define __RANGE__ITERATION_4 __RANGE__ITERATION_3, 3
#define __RANGE__ITERATION_5 __RANGE__ITERATION_4, 4
#define __RANGE__ITERATION_6 __RANGE__ITERATION_5, 5
#define __RANGE__ITERATION_7 __RANGE__ITERATION_6, 6
#define __RANGE__ITERATION_8 __RANGE__ITERATION_7, 7
#define __RANGE__ITERATION_9 __RANGE__ITERATION_8, 8
#define __RANGE__ITERATION_10 __RANGE__ITERATION_9, 9
#define __RANGE__ITERATION_11 __RANGE__ITERATION_10, 10
#define __RANGE__ITERATION_12 __RANGE__ITERATION_11, 11
#define __RANGE__ITERATION_13 __RANGE__ITERATION_12, 12
#define __RANGE__ITERATION_14 __RANGE__ITERATION_13, 13
#define __RANGE__ITERATION_15 __RANGE__ITERATION_14, 14
#define __RANGE__ITERATION_16 __RANGE__ITERATION_15, 15
#define __RANGE__ITERATION_N_NOEXPAND(size) __RANGE__ITERATION_##size
#define RANGE(size) __RANGE__ITERATION_N_NOEXPAND(size)
