#pragma once

#include <helpers/ForEachMacro.h>


#define __TERNARY__SECOND_NOEXPAND(a, b, ...) b
#define __TERNARY__SECOND(...) __TERNARY__SECOND_NOEXPAND(__VA_ARGS__)

#define __TERNARY__HELPER_MACRO_ _, FALSE
#define __TERNARY__IS_NON_EMPTY_NOEXPAND(CONDITION) __TERNARY__SECOND(__TERNARY__HELPER_MACRO_##CONDITION, TRUE)
#define __TERNARY__IS_NON_EMPTY(CONDITION) __TERNARY__IS_NON_EMPTY_NOEXPAND(CONDITION)

#define __TERNARY__FALSE(TRUE_CASE, FALSE_CASE) FALSE_CASE
#define __TERNARY__TRUE(TRUE_CASE, FALSE_CASE) TRUE_CASE

#define __TERNARY__IMPL_NOEXPAND(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY__##BOOLEAN(FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY__IMPL(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY__IMPL_NOEXPAND(BOOLEAN, FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY__ONE_COND(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY__IMPL(__TERNARY__IS_NON_EMPTY(CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define TERNARY(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY__ONE_COND(JOIN(ù, CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))


#define __TERNARY2__SECOND_NOEXPAND(a, b, ...) b
#define __TERNARY2__SECOND(...) __TERNARY2__SECOND_NOEXPAND(__VA_ARGS__)

#define __TERNARY2__HELPER_MACRO_ _, FALSE
#define __TERNARY2__IS_NON_EMPTY_NOEXPAND(CONDITION) __TERNARY2__SECOND(__TERNARY2__HELPER_MACRO_##CONDITION, TRUE)
#define __TERNARY2__IS_NON_EMPTY(CONDITION) __TERNARY2__IS_NON_EMPTY_NOEXPAND(CONDITION)

#define __TERNARY2__FALSE(TRUE_CASE, FALSE_CASE) FALSE_CASE
#define __TERNARY2__TRUE(TRUE_CASE, FALSE_CASE) TRUE_CASE

#define __TERNARY2__IMPL_NOEXPAND(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY2__##BOOLEAN(FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY2__IMPL(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY2__IMPL_NOEXPAND(BOOLEAN, FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY2__ONE_COND(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY2__IMPL(__TERNARY2__IS_NON_EMPTY(CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define TERNARY2(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY2__ONE_COND(JOIN(ù, CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))


#define __TERNARY3__SECOND_NOEXPAND(a, b, ...) b
#define __TERNARY3__SECOND(...) __TERNARY3__SECOND_NOEXPAND(__VA_ARGS__)

#define __TERNARY3__HELPER_MACRO_ _, FALSE
#define __TERNARY3__IS_NON_EMPTY_NOEXPAND(CONDITION) __TERNARY3__SECOND(__TERNARY3__HELPER_MACRO_##CONDITION, TRUE)
#define __TERNARY3__IS_NON_EMPTY(CONDITION) __TERNARY3__IS_NON_EMPTY_NOEXPAND(CONDITION)

#define __TERNARY3__FALSE(TRUE_CASE, FALSE_CASE) FALSE_CASE
#define __TERNARY3__TRUE(TRUE_CASE, FALSE_CASE) TRUE_CASE

#define __TERNARY3__IMPL_NOEXPAND(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY3__##BOOLEAN(FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY3__IMPL(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY3__IMPL_NOEXPAND(BOOLEAN, FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY3__ONE_COND(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY3__IMPL(__TERNARY3__IS_NON_EMPTY(CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define TERNARY3(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY3__ONE_COND(JOIN(ù, CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))


#define __TERNARY4__SECOND_NOEXPAND(a, b, ...) b
#define __TERNARY4__SECOND(...) __TERNARY4__SECOND_NOEXPAND(__VA_ARGS__)

#define __TERNARY4__HELPER_MACRO_ _, FALSE
#define __TERNARY4__IS_NON_EMPTY_NOEXPAND(CONDITION) __TERNARY4__SECOND(__TERNARY4__HELPER_MACRO_##CONDITION, TRUE)
#define __TERNARY4__IS_NON_EMPTY(CONDITION) __TERNARY4__IS_NON_EMPTY_NOEXPAND(CONDITION)

#define __TERNARY4__FALSE(TRUE_CASE, FALSE_CASE) FALSE_CASE
#define __TERNARY4__TRUE(TRUE_CASE, FALSE_CASE) TRUE_CASE

#define __TERNARY4__IMPL_NOEXPAND(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY4__##BOOLEAN(FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY4__IMPL(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY4__IMPL_NOEXPAND(BOOLEAN, FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY4__ONE_COND(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY4__IMPL(__TERNARY4__IS_NON_EMPTY(CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define TERNARY4(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY4__ONE_COND(JOIN(ù, CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))


#define __TERNARY5__SECOND_NOEXPAND(a, b, ...) b
#define __TERNARY5__SECOND(...) __TERNARY5__SECOND_NOEXPAND(__VA_ARGS__)

#define __TERNARY5__HELPER_MACRO_ _, FALSE
#define __TERNARY5__IS_NON_EMPTY_NOEXPAND(CONDITION) __TERNARY5__SECOND(__TERNARY5__HELPER_MACRO_##CONDITION, TRUE)
#define __TERNARY5__IS_NON_EMPTY(CONDITION) __TERNARY5__IS_NON_EMPTY_NOEXPAND(CONDITION)

#define __TERNARY5__FALSE(TRUE_CASE, FALSE_CASE) FALSE_CASE
#define __TERNARY5__TRUE(TRUE_CASE, FALSE_CASE) TRUE_CASE

#define __TERNARY5__IMPL_NOEXPAND(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY5__##BOOLEAN(FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY5__IMPL(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY5__IMPL_NOEXPAND(BOOLEAN, FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY5__ONE_COND(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY5__IMPL(__TERNARY5__IS_NON_EMPTY(CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define TERNARY5(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY5__ONE_COND(JOIN(ù, CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))


#define __TERNARY6__SECOND_NOEXPAND(a, b, ...) b
#define __TERNARY6__SECOND(...) __TERNARY6__SECOND_NOEXPAND(__VA_ARGS__)

#define __TERNARY6__HELPER_MACRO_ _, FALSE
#define __TERNARY6__IS_NON_EMPTY_NOEXPAND(CONDITION) __TERNARY6__SECOND(__TERNARY6__HELPER_MACRO_##CONDITION, TRUE)
#define __TERNARY6__IS_NON_EMPTY(CONDITION) __TERNARY6__IS_NON_EMPTY_NOEXPAND(CONDITION)

#define __TERNARY6__FALSE(TRUE_CASE, FALSE_CASE) FALSE_CASE
#define __TERNARY6__TRUE(TRUE_CASE, FALSE_CASE) TRUE_CASE

#define __TERNARY6__IMPL_NOEXPAND(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY6__##BOOLEAN(FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY6__IMPL(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY6__IMPL_NOEXPAND(BOOLEAN, FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY6__ONE_COND(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY6__IMPL(__TERNARY6__IS_NON_EMPTY(CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define TERNARY6(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY6__ONE_COND(JOIN(ù, CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))


#define __TERNARY7__SECOND_NOEXPAND(a, b, ...) b
#define __TERNARY7__SECOND(...) __TERNARY7__SECOND_NOEXPAND(__VA_ARGS__)

#define __TERNARY7__HELPER_MACRO_ _, FALSE
#define __TERNARY7__IS_NON_EMPTY_NOEXPAND(CONDITION) __TERNARY7__SECOND(__TERNARY7__HELPER_MACRO_##CONDITION, TRUE)
#define __TERNARY7__IS_NON_EMPTY(CONDITION) __TERNARY7__IS_NON_EMPTY_NOEXPAND(CONDITION)

#define __TERNARY7__FALSE(TRUE_CASE, FALSE_CASE) FALSE_CASE
#define __TERNARY7__TRUE(TRUE_CASE, FALSE_CASE) TRUE_CASE

#define __TERNARY7__IMPL_NOEXPAND(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY7__##BOOLEAN(FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY7__IMPL(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY7__IMPL_NOEXPAND(BOOLEAN, FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY7__ONE_COND(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY7__IMPL(__TERNARY7__IS_NON_EMPTY(CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define TERNARY7(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY7__ONE_COND(JOIN(ù, CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))


#define __TERNARY8__SECOND_NOEXPAND(a, b, ...) b
#define __TERNARY8__SECOND(...) __TERNARY8__SECOND_NOEXPAND(__VA_ARGS__)

#define __TERNARY8__HELPER_MACRO_ _, FALSE
#define __TERNARY8__IS_NON_EMPTY_NOEXPAND(CONDITION) __TERNARY8__SECOND(__TERNARY8__HELPER_MACRO_##CONDITION, TRUE)
#define __TERNARY8__IS_NON_EMPTY(CONDITION) __TERNARY8__IS_NON_EMPTY_NOEXPAND(CONDITION)

#define __TERNARY8__FALSE(TRUE_CASE, FALSE_CASE) FALSE_CASE
#define __TERNARY8__TRUE(TRUE_CASE, FALSE_CASE) TRUE_CASE

#define __TERNARY8__IMPL_NOEXPAND(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY8__##BOOLEAN(FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY8__IMPL(BOOLEAN, TRUE_CASE, FALSE_CASE) __TERNARY8__IMPL_NOEXPAND(BOOLEAN, FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define __TERNARY8__ONE_COND(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY8__IMPL(__TERNARY8__IS_NON_EMPTY(CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
#define TERNARY8(CONDITION, TRUE_CASE, FALSE_CASE) __TERNARY8__ONE_COND(JOIN(ù, CONDITION), FORWARD(TRUE_CASE), FORWARD(FALSE_CASE))
