#pragma once

#include <tensor/TensorMapKeyEnum.h>

#include <plugins/natives/api.h>

#include <rtti/TypenameArgId.h>

#define TENSOR_MAP_KEY_ENUM__VALUES_OF_TensorSingleton SINGLE_TENSOR
DECLARE_TENSOR_MAP_KEY_ENUM(TensorSingleton, MY_NEURAL_NETWORK_LIB__NATIVES__API)

DECLARE_AS_TYPENAME_ARG(TensorSingleton, 0x00000011)

#define TENSOR_MAP_KEY_ENUM__VALUES_OF_TensorPair FIRST_TENSOR, SECOND_TENSOR
DECLARE_TENSOR_MAP_KEY_ENUM(TensorPair, MY_NEURAL_NETWORK_LIB__NATIVES__API)

DECLARE_AS_TYPENAME_ARG(TensorPair, 0x00000012)

#define TENSOR_MAP_KEY_ENUM__VALUES_OF_PerceptronParamsKeyEnum WEIGHTS, BIASES
DECLARE_TENSOR_MAP_KEY_ENUM(PerceptronParamsKeyEnum, MY_NEURAL_NETWORK_LIB__NATIVES__API)

DECLARE_AS_TYPENAME_ARG(PerceptronParamsKeyEnum, 0x00000013)
