#pragma once

#include <module/ModuleMacros.h>

#include <module/AbstractModule.impl.cuh>
#include <module/TensorKernelWrapper.cuh>

#include <stdexcept>

#include <tensor/TensorMap.h>

// Check tensors validity

#define __IMPLEMENT_MODULE__GET_AND_CHECK_TENSOR_MAPS__LOCAL_MAP_VAR_NAME(mapName) __IMPLEMENT_MODULE__GET_AND_CHECK_TENSOR_MAPS__##mapName

#define __IMPLEMENT_MODULE__CHECK_DIMENSION_NOEXPAND(KEY_ENUM_VALUE, ExpectedDimension, mapPtr, ConcreteModuleName, ValueType, KeyEnum)     \
    if (dynamic_cast<const Tensor<ValueType, ExpectedDimension>*>(&(mapPtr)->get(KeyEnum::Values::KEY_ENUM_VALUE)) == nullptr)              \
        throw std::runtime_error(#ConcreteModuleName ": " #mapPtr "'s tensor for key " #KEY_ENUM_VALUE " not set or has wrong dimension.");

#define __IMPLEMENT_MODULE__CHECK_DIMENSION(iteratedPack, mapPtr, ConcreteModuleName, ValueType, KeyEnum)                                                 \
    __MODULE__UNPACK2(PACK(__IMPLEMENT_MODULE__CHECK_DIMENSION_NOEXPAND)(__MODULE__UNPACK(iteratedPack), mapPtr, ConcreteModuleName, ValueType, KeyEnum))

#define __IMPLEMENT_MODULE__CHECK_DIMENSIONS_FROM_TENSOR_MAP(ConcreteModuleName, ValueType, localMapVarName, mapPtr, KeyEnum, TensorDimensionsPack) \
    const TensorMap<ValueType, KeyEnum>* localMapVarName = static_cast<const TensorMap<ValueType, KeyEnum>*>(mapPtr);                               \
    if (localMapVarName == nullptr)                                                                                                                 \
        throw std::runtime_error(#ConcreteModuleName ": cost partial derivative with respect to input map not set or has the wrong type");          \
                                                                                                                                                    \
    FOR_EACH_SEP3(                                                                                                                                  \
        __IMPLEMENT_MODULE__CHECK_DIMENSION,                                                                                                        \
        FORWARD(),                                                                                                                                  \
        FORWARD(localMapVarName, ConcreteModuleName, ValueType, KeyEnum),                                                                           \
        INTERTWINE_PACKS12(                                                                                                                         \
            PACK(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_VALUES(KeyEnum)),                                                                               \
            TensorDimensionsPack                                                                                                                    \
        )                                                                                                                                           \
    )

#define __IMPLEMENT_MODULE__GET_AND_CHECK_TENSOR_MAPS(ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)                             \
    __IMPLEMENT_MODULE__CHECK_DIMENSIONS_FROM_TENSOR_MAP(ConcreteModuleName, ValueType, __IMPLEMENT_MODULE__GET_AND_CHECK_TENSOR_MAPS__LOCAL_MAP_VAR_NAME(parameterMap), (&getParameterTensorMap()), ParameterKeyEnum, ParameterTensorDimensionsPack) \
    __IMPLEMENT_MODULE__CHECK_DIMENSIONS_FROM_TENSOR_MAP(ConcreteModuleName, ValueType, __IMPLEMENT_MODULE__GET_AND_CHECK_TENSOR_MAPS__LOCAL_MAP_VAR_NAME(inputMap), getInputTensorMap(), InputKeyEnum, InputTensorDimensionsPack)                    \
    __IMPLEMENT_MODULE__CHECK_DIMENSIONS_FROM_TENSOR_MAP(ConcreteModuleName, ValueType, __IMPLEMENT_MODULE__GET_AND_CHECK_TENSOR_MAPS__LOCAL_MAP_VAR_NAME(outputMap), getOutputTensorMap(), OutputKeyEnum, OutputTensorDimensionsPack)                \
                                                                                                                                                                                                                                                      \
    if (!areSizesCorrect(getInputTensorSizes(), getParameterTensorSizes(), getOutputTensorSizes()))                                                                                                                                                   \
        throw std::runtime_error(#ConcreteModuleName ": invalid tensor sizes");

#define __IMPLEMENT_MODULE__CHECK_COST_PART_DERIV_MAP(KEY_ENUM_VALUE, Dimension, mapPtr, expectedMapPtr, ConcreteModuleName, ValueType, KeyEnum)                                                                                                                                           \
    if (static_cast<const Tensor<ValueType, Dimension>*>(&static_cast<const TensorMap<ValueType, KeyEnum>*>(mapPtr)->get(KeyEnum::Values::KEY_ENUM_VALUE))->sizes() != static_cast<const Tensor<ValueType, Dimension>*>(&(expectedMapPtr)->get(KeyEnum::Values::KEY_ENUM_VALUE))->sizes()) \
        throw std::runtime_error(#ConcreteModuleName ": " #mapPtr "'s tensor for key " #KEY_ENUM_VALUE " does not have the same size as " #expectedMapPtr "'s tensor for key " #KEY_ENUM_VALUE ".");

#define __IMPLEMENT_MODULE__CHECK_COST_PART_DERIV_MAP_PACKED(pack, mapPtr, expectedMapPtr, ConcreteModuleName, ValueType, KeyEnum)                                 \
    __MODULE__UNPACK2(PACK(__IMPLEMENT_MODULE__CHECK_COST_PART_DERIV_MAP)(__MODULE__UNPACK(pack), mapPtr, expectedMapPtr, ConcreteModuleName, ValueType, KeyEnum))

#define __IMPLEMENT_MODULE__CHECK_COST_PART_DERIV_MAPS(costPartDerivWRTInput, costPartDerivWRTParameter, costPartDerivWRTOutput, ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack) \
    __IMPLEMENT_MODULE__GET_AND_CHECK_TENSOR_MAPS(ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)                                                                                \
                                                                                                                                                                                                                                                                                                     \
    FOR_EACH_SEP3(                                                                                                                                                                                                                                                                                   \
        __IMPLEMENT_MODULE__CHECK_COST_PART_DERIV_MAP_PACKED,                                                                                                                                                                                                                                        \
        FORWARD(),                                                                                                                                                                                                                                                                                   \
        FORWARD(&costPartDerivWRTInput, getInputTensorMap(), ConcreteModuleName, ValueType, InputKeyEnum),                                                                                                                                                                                           \
        INTERTWINE_PACKS12(                                                                                                                                                                                                                                                                          \
            PACK(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_VALUES(InputKeyEnum)),                                                                                                                                                                                                                           \
            InputTensorDimensionsPack                                                                                                                                                                                                                                                                \
        )                                                                                                                                                                                                                                                                                            \
    )                                                                                                                                                                                                                                                                                                \
                                                                                                                                                                                                                                                                                                     \
    FOR_EACH_SEP3(                                                                                                                                                                                                                                                                                   \
        __IMPLEMENT_MODULE__CHECK_COST_PART_DERIV_MAP_PACKED,                                                                                                                                                                                                                                        \
        FORWARD(),                                                                                                                                                                                                                                                                                   \
        FORWARD(&costPartDerivWRTParameter, &getParameterTensorMap(), ConcreteModuleName, ValueType, ParameterKeyEnum),                                                                                                                                                                              \
        INTERTWINE_PACKS12(                                                                                                                                                                                                                                                                          \
            PACK(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_VALUES(ParameterKeyEnum)),                                                                                                                                                                                                                       \
            ParameterTensorDimensionsPack                                                                                                                                                                                                                                                            \
        )                                                                                                                                                                                                                                                                                            \
    )                                                                                                                                                                                                                                                                                                \
                                                                                                                                                                                                                                                                                                     \
    FOR_EACH_SEP3(                                                                                                                                                                                                                                                                                   \
        __IMPLEMENT_MODULE__CHECK_COST_PART_DERIV_MAP_PACKED,                                                                                                                                                                                                                                        \
        FORWARD(),                                                                                                                                                                                                                                                                                   \
        FORWARD(&costPartDerivWRTOutput, getOutputTensorMap(), ConcreteModuleName, ValueType, OutputKeyEnum),                                                                                                                                                                                        \
        INTERTWINE_PACKS12(                                                                                                                                                                                                                                                                          \
            PACK(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_VALUES(OutputKeyEnum)),                                                                                                                                                                                                                          \
            OutputTensorDimensionsPack                                                                                                                                                                                                                                                               \
        )                                                                                                                                                                                                                                                                                            \
    )

////////////////////////////
// Computation kernel method

/// Kernel name

#define __IMPLEMENT_MODULE__COMPUTATION_KERNEL_NAME_FROM_ENUM_VALUE_NAME_NOEXPAND(ENUM_VALUE, ConcreteModuleName) __##ConcreteModuleName##__computationKernel__##ENUM_VALUE
#define __IMPLEMENT_MODULE__COMPUTATION_KERNEL_NAME_FROM_ENUM_VALUE_NAME(ENUM_VALUE, ConcreteModuleName) __IMPLEMENT_MODULE__COMPUTATION_KERNEL_NAME_FROM_ENUM_VALUE_NAME_NOEXPAND(ENUM_VALUE, ConcreteModuleName)
#define __IMPLEMENT_MODULE__COMPUTATION_KERNEL_NAME_FROM_INDEX(index, OutputKeyEnum, ConcreteModuleName) __IMPLEMENT_MODULE__COMPUTATION_KERNEL_NAME_FROM_ENUM_VALUE_NAME(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_GET_VALUE_NAME(OutputKeyEnum, index), ConcreteModuleName)

/// Passed arguments

#define __IMPLEMENT_MODULE__COMPUTATION_KERNEL__ARGUMENT(index, mapPtr, ValueType, DimensionsPack, KeyEnum, constQualifier)                                                                                                                                                       \
    static_cast<constQualifier Tensor<ValueType, GET_FROM_INDEX(index, __MODULE__UNPACK(DimensionsPack))>*>(&static_cast<constQualifier TensorMap<ValueType, KeyEnum>*>(mapPtr)->get(KeyEnum::Values::GET_FROM_INDEX(index, TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_VALUES(KeyEnum))))

#define __IMPLEMENT_MODULE__COMPUTATION_KERNEL__ARGUMENTS(index, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)                               \
    __IMPLEMENT_MODULE__COMPUTATION_KERNEL__ARGUMENT(index, getOutputTensorMap(), ValueType, OutputTensorDimensionsPack, OutputKeyEnum, ),                                                                                                     \
    FOR_EACH(__IMPLEMENT_MODULE__COMPUTATION_KERNEL__ARGUMENT, FORWARD((&getParameterTensorMap()), ValueType, ParameterTensorDimensionsPack, ParameterKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(ParameterKeyEnum))), \
    FOR_EACH(__IMPLEMENT_MODULE__COMPUTATION_KERNEL__ARGUMENT, FORWARD(getInputTensorMap(), ValueType, InputTensorDimensionsPack, InputKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(InputKeyEnum)))

///////////////////////////////////////////
// Computation kernel method implementation

#define __IMPLEMENT_MODULE__IMPLEMENT_COMPUTATION_KERNEL(index, ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                               \
    namespace                                                                                                                                                                                                                                                                                                                     \
    {                                                                                                                                                                                                                                                                                                                             \
        TEMPLATE_MACROS__TEMPLATE_PREFIX(TemplateParamTypesPack, TemplateParamNamesPack)                                                                                                                                                                                                                                          \
        GLOBAL void __IMPLEMENT_MODULE__COMPUTATION_KERNEL_NAME_FROM_INDEX(index, OutputKeyEnum, ConcreteModuleName)(__IMPLEMENT_MODULE__COMPUTATION_KERNEL__NAMED_PARAMS(index, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)) \
        {                                                                                                                                                                                                                                                                                                                         \
            TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(ConcreteModuleName, TemplateParamTypesPack, TemplateParamNamesPack)::__MODULE__COMPUTATION_KERNEL_NAME_FROM_INDEX(index, OutputKeyEnum)(__IMPLEMENT_MODULE__COMPUTATION_KERNEL__PARAMS_NAMES(index, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum));                          \
        }                                                                                                                                                                                                                                                                                                                         \
    }

#define __IMPLEMENT_MODULE__CALL_COMPUTATION_KERNEL(index, ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                                                             \
    TensorKernelWrapper<ValueType, __IMPLEMENT_MODULE__COMPUTATION_KERNEL__OUTPUT_TENSOR_DIMENSION(index, OutputTensorDimensionsPack), __IMPLEMENT_MODULE__COMPUTATION_KERNEL__INPUT_TENSOR_DIMENSIONS(InputTensorDimensionsPack, ParameterTensorDimensionsPack)>::call(                                                                                   \
        [](                                                                                                                                                                                                                                                                                                                                                \
            const dim3 nbBlocks,                                                                                                                                                                                                                                                                                                                           \
            const dim3 nbThreads,                                                                                                                                                                                                                                                                                                                          \
            cudaStream_t stream,                                                                                                                                                                                                                                                                                                                           \
            const RawTuple<__IMPLEMENT_MODULE__COMPUTATION_KERNEL__PARAMS_TYPES(index, ValueType, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)> tensorsTuple,                                                                                                                                                     \
            const RawTuple<> contextArgs                                                                                                                                                                                                                                                                                                                   \
        )                                                                                                                                                                                                                                                                                                                                                  \
        {                                                                                                                                                                                                                                                                                                                                                  \
            tensorsTuple.hostApply([nbBlocks, nbThreads, stream](__IMPLEMENT_MODULE__COMPUTATION_KERNEL__NAMED_PARAMS(index, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)) {                                                                            \
                TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(__IMPLEMENT_MODULE__COMPUTATION_KERNEL_NAME_FROM_INDEX(index, OutputKeyEnum, ConcreteModuleName), TemplateParamTypesPack, TemplateParamNamesPack)<<<nbBlocks, nbThreads, 0, stream>>>(__IMPLEMENT_MODULE__COMPUTATION_KERNEL__PARAMS_NAMES(index, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum)); \
            });                                                                                                                                                                                                                                                                                                                                            \
        },                                                                                                                                                                                                                                                                                                                                                 \
        makeRawTuple(__IMPLEMENT_MODULE__COMPUTATION_KERNEL__ARGUMENTS(index, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)),                                                                                                                            \
        getInputBackpropagationMemory()                                                                                                                                                                                                                                                                                                                    \
    );

#define __IMPLEMENT_MODULE__COMPUTE(ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack) \
    FOR_EACH_SEP5(                                                                                                                                                                                                                                      \
        __IMPLEMENT_MODULE__IMPLEMENT_COMPUTATION_KERNEL,                                                                                                                                                                                               \
        FORWARD(),                                                                                                                                                                                                                                      \
        FORWARD(                                                                                                                                                                                                                                        \
            ConcreteModuleName,                                                                                                                                                                                                                         \
            ValueType,                                                                                                                                                                                                                                  \
            InputKeyEnum,                                                                                                                                                                                                                               \
            ParameterKeyEnum,                                                                                                                                                                                                                           \
            OutputKeyEnum,                                                                                                                                                                                                                              \
            InputTensorDimensionsPack,                                                                                                                                                                                                                  \
            ParameterTensorDimensionsPack,                                                                                                                                                                                                              \
            OutputTensorDimensionsPack,                                                                                                                                                                                                                 \
            TemplateParamTypesPack,                                                                                                                                                                                                                     \
            TemplateParamNamesPack                                                                                                                                                                                                                      \
        ),                                                                                                                                                                                                                                              \
        RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(OutputKeyEnum))                                                                                                                                                                              \
    )                                                                                                                                                                                                                                                   \
                                                                                                                                                                                                                                                        \
    TEMPLATE_MACROS__TEMPLATE_PREFIX(TemplateParamTypesPack, TemplateParamNamesPack)                                                                                                                                                                    \
    HOST                                                                                                                                                                                                                                                \
    void                                                                                                                                                                                                                                                \
    TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(ConcreteModuleName, TemplateParamTypesPack, TemplateParamNamesPack)::compute() const                                                                                                                        \
    {                                                                                                                                                                                                                                                   \
        __IMPLEMENT_MODULE__GET_AND_CHECK_TENSOR_MAPS(ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)                               \
                                                                                                                                                                                                                                                        \
        FOR_EACH_SEP5(                                                                                                                                                                                                                                  \
            __IMPLEMENT_MODULE__CALL_COMPUTATION_KERNEL,                                                                                                                                                                                                \
            FORWARD(),                                                                                                                                                                                                                                  \
            FORWARD(                                                                                                                                                                                                                                    \
                ConcreteModuleName,                                                                                                                                                                                                                     \
                ValueType,                                                                                                                                                                                                                              \
                InputKeyEnum,                                                                                                                                                                                                                           \
                ParameterKeyEnum,                                                                                                                                                                                                                       \
                OutputKeyEnum,                                                                                                                                                                                                                          \
                InputTensorDimensionsPack,                                                                                                                                                                                                              \
                ParameterTensorDimensionsPack,                                                                                                                                                                                                          \
                OutputTensorDimensionsPack,                                                                                                                                                                                                             \
                TemplateParamTypesPack,                                                                                                                                                                                                                 \
                TemplateParamNamesPack                                                                                                                                                                                                                  \
            ),                                                                                                                                                                                                                                          \
            RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(OutputKeyEnum))                                                                                                                                                                          \
        )                                                                                                                                                                                                                                               \
    }

/////////////////////////
// Backpropagation method

/// Kernel names

#define __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_NAME_FROM_ENUM_VALUE_NAME_NOEXPAND(ENUM_VALUE, ConcreteModuleName) __##ConcreteModuleName##__inputBackpropagationKernel__##ENUM_VALUE
#define __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_NAME_FROM_ENUM_VALUE_NAME(ENUM_VALUE, ConcreteModuleName) __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_NAME_FROM_ENUM_VALUE_NAME_NOEXPAND(ENUM_VALUE, ConcreteModuleName)
#define __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_NAME_FROM_INDEX(index, InputKeyEnum, ConcreteModuleName) __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_NAME_FROM_ENUM_VALUE_NAME(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_GET_VALUE_NAME(InputKeyEnum, index), ConcreteModuleName)

#define __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_NAME_FROM_ENUM_VALUE_NAME_NOEXPAND(ENUM_VALUE, ConcreteModuleName) __##ConcreteModuleName##__parameterBackpropagationKernel__##ENUM_VALUE
#define __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_NAME_FROM_ENUM_VALUE_NAME(ENUM_VALUE, ConcreteModuleName) __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_NAME_FROM_ENUM_VALUE_NAME_NOEXPAND(ENUM_VALUE, ConcreteModuleName)
#define __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_NAME_FROM_INDEX(index, ParameterKeyEnum, ConcreteModuleName) __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_NAME_FROM_ENUM_VALUE_NAME(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_GET_VALUE_NAME(ParameterKeyEnum, index), ConcreteModuleName)

/// Passed arguments

#define __IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT(index, mapPtr, ValueType, DimensionsPack, KeyEnum, constQualifier)                                                                                                                                                   \
    static_cast<constQualifier Tensor<ValueType, GET_FROM_INDEX(index, __MODULE__UNPACK(DimensionsPack))>*>(&static_cast<constQualifier TensorMap<ValueType, KeyEnum>*>(mapPtr)->get(KeyEnum::Values::GET_FROM_INDEX(index, TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_VALUES(KeyEnum))))

#define __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__ARGUMENTS(index, costPartDerivWRTInput, costPartDerivWRTOutput, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack) \
    __IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT(index, (&costPartDerivWRTInput), ValueType, InputTensorDimensionsPack, InputKeyEnum, ),                                                                                                                          \
    FOR_EACH(__IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT, FORWARD((&costPartDerivWRTOutput), ValueType, OutputTensorDimensionsPack, OutputKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(OutputKeyEnum))),                                  \
    FOR_EACH(__IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT, FORWARD(getOutputTensorMap(), ValueType, OutputTensorDimensionsPack, OutputKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(OutputKeyEnum))),                                       \
    FOR_EACH(__IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT, FORWARD((&getParameterTensorMap()), ValueType, ParameterTensorDimensionsPack, ParameterKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(ParameterKeyEnum))),                        \
    FOR_EACH(__IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT, FORWARD(getInputTensorMap(), ValueType, InputTensorDimensionsPack, InputKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(InputKeyEnum)))

#define __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__ARGUMENTS(index, costPartDerivWRTParameter, costPartDerivWRTOutput, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack) \
    __IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT(index, (&costPartDerivWRTParameter), ValueType, ParameterTensorDimensionsPack, ParameterKeyEnum, ),                                                                                                                  \
    FOR_EACH(__IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT, FORWARD((&costPartDerivWRTOutput), ValueType, OutputTensorDimensionsPack, OutputKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(OutputKeyEnum))),                                      \
    FOR_EACH(__IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT, FORWARD(getOutputTensorMap(), ValueType, OutputTensorDimensionsPack, OutputKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(OutputKeyEnum))),                                           \
    FOR_EACH(__IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT, FORWARD((&getParameterTensorMap()), ValueType, ParameterTensorDimensionsPack, ParameterKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(ParameterKeyEnum))),                            \
    FOR_EACH(__IMPLEMENT_MODULE__BACKPROPAGATION_KERNEL__ARGUMENT, FORWARD(getInputTensorMap(), ValueType, InputTensorDimensionsPack, InputKeyEnum, const), RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(InputKeyEnum)))

/////////////////////////////////////////
// Backpropagation kernels implementation

/// Input

#define __IMPLEMENT_MODULE__IMPLEMENT_INPUT_BACKPROPAGATION_KERNEL(index, ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                                 \
    namespace                                                                                                                                                                                                                                                                                                                                 \
    {                                                                                                                                                                                                                                                                                                                                         \
        TEMPLATE_MACROS__TEMPLATE_PREFIX(TemplateParamTypesPack, TemplateParamNamesPack)                                                                                                                                                                                                                                                      \
        GLOBAL void __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_NAME_FROM_INDEX(index, InputKeyEnum, ConcreteModuleName)(__IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__NAMED_PARAMS(index, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)) \
        {                                                                                                                                                                                                                                                                                                                                     \
            TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(ConcreteModuleName, TemplateParamTypesPack, TemplateParamNamesPack)::__MODULE__INPUT_BACKPROPAGATION_KERNEL_NAME_FROM_INDEX(index, InputKeyEnum)(__IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__PARAMS_NAMES(index, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum));                   \
        }                                                                                                                                                                                                                                                                                                                                     \
    }

#define __IMPLEMENT_MODULE__CALL_INPUT_BACKPROPAGATION_KERNEL(index, costPartDerivWRTInput, costPartDerivWRTOutput, ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                \
    TensorKernelWrapper<ValueType, __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__OUTPUT_TENSOR_DIMENSION(index, InputTensorDimensionsPack), __IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__INPUT_TENSOR_DIMENSIONS(InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)>::call(                                                \
        [](                                                                                                                                                                                                                                                                                                                                                            \
            const dim3 nbBlocks,                                                                                                                                                                                                                                                                                                                                       \
            const dim3 nbThreads,                                                                                                                                                                                                                                                                                                                                      \
            cudaStream_t stream,                                                                                                                                                                                                                                                                                                                                       \
            const RawTuple<__IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__PARAMS_TYPES(index, ValueType, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)> tensorsTuple,                                                                                                                                                       \
            const RawTuple<> contextArgs                                                                                                                                                                                                                                                                                                                               \
        )                                                                                                                                                                                                                                                                                                                                                              \
        {                                                                                                                                                                                                                                                                                                                                                              \
            tensorsTuple.hostApply([nbBlocks, nbThreads, stream](__IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__NAMED_PARAMS(index, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)) {                                                                              \
                TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(__IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_NAME_FROM_INDEX(index, InputKeyEnum, ConcreteModuleName), TemplateParamTypesPack, TemplateParamNamesPack)<<<nbBlocks, nbThreads, 0, stream>>>(__IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__PARAMS_NAMES(index, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum)); \
            });                                                                                                                                                                                                                                                                                                                                                        \
        },                                                                                                                                                                                                                                                                                                                                                             \
        makeRawTuple(__IMPLEMENT_MODULE__INPUT_BACKPROPAGATION_KERNEL__ARGUMENTS(index, costPartDerivWRTInput, costPartDerivWRTOutput, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)),                                                                               \
        getInputBackpropagationMemory()                                                                                                                                                                                                                                                                                                                                \
    );

/// Parameter

#define __IMPLEMENT_MODULE__IMPLEMENT_PARAM_BACKPROPAGATION_KERNEL(index, ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                                     \
    namespace                                                                                                                                                                                                                                                                                                                                     \
    {                                                                                                                                                                                                                                                                                                                                             \
        TEMPLATE_MACROS__TEMPLATE_PREFIX(TemplateParamTypesPack, TemplateParamNamesPack)                                                                                                                                                                                                                                                          \
        GLOBAL void __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_NAME_FROM_INDEX(index, ParameterKeyEnum, ConcreteModuleName)(__IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__NAMED_PARAMS(index, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)) \
        {                                                                                                                                                                                                                                                                                                                                         \
            TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(ConcreteModuleName, TemplateParamTypesPack, TemplateParamNamesPack)::__MODULE__PARAM_BACKPROPAGATION_KERNEL_NAME_FROM_INDEX(index, ParameterKeyEnum)(__IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__PARAMS_NAMES(index, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum));                   \
        }                                                                                                                                                                                                                                                                                                                                         \
    }

#define __IMPLEMENT_MODULE__CALL_PARAM_BACKPROPAGATION_KERNEL(index, costPartDerivWRTInput, costPartDerivWRTOutput, ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                    \
    TensorKernelWrapper<ValueType, __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__OUTPUT_TENSOR_DIMENSION(index, ParameterTensorDimensionsPack), __IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__INPUT_TENSOR_DIMENSIONS(InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)>::call(                                                \
        [](                                                                                                                                                                                                                                                                                                                                                                \
            const dim3 nbBlocks,                                                                                                                                                                                                                                                                                                                                           \
            const dim3 nbThreads,                                                                                                                                                                                                                                                                                                                                          \
            cudaStream_t stream,                                                                                                                                                                                                                                                                                                                                           \
            const RawTuple<__IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__PARAMS_TYPES(index, ValueType, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)> tensorsTuple,                                                                                                                                                           \
            const RawTuple<> contextArgs                                                                                                                                                                                                                                                                                                                                   \
        )                                                                                                                                                                                                                                                                                                                                                                  \
        {                                                                                                                                                                                                                                                                                                                                                                  \
            tensorsTuple.hostApply([nbBlocks, nbThreads, stream](__IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__NAMED_PARAMS(index, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)) {                                                                                  \
                TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(__IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_NAME_FROM_INDEX(index, ParameterKeyEnum, ConcreteModuleName), TemplateParamTypesPack, TemplateParamNamesPack)<<<nbBlocks, nbThreads, 0, stream>>>(__IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__PARAMS_NAMES(index, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum)); \
            });                                                                                                                                                                                                                                                                                                                                                            \
        },                                                                                                                                                                                                                                                                                                                                                                 \
        makeRawTuple(__IMPLEMENT_MODULE__PARAM_BACKPROPAGATION_KERNEL__ARGUMENTS(index, costPartDerivWRTInput, costPartDerivWRTOutput, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack)),                                                                                   \
        getParameterBackpropagationMemory()                                                                                                                                                                                                                                                                                                                                \
    );

/// Method implementation

#define __IMPLEMENT_MODULE__BACKPROPAGATE(ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                                  \
    FOR_EACH_SEP5(                                                                                                                                                                                                                                                                                             \
        __IMPLEMENT_MODULE__IMPLEMENT_INPUT_BACKPROPAGATION_KERNEL,                                                                                                                                                                                                                                            \
        FORWARD(),                                                                                                                                                                                                                                                                                             \
        FORWARD(                                                                                                                                                                                                                                                                                               \
            ConcreteModuleName,                                                                                                                                                                                                                                                                                \
            ValueType,                                                                                                                                                                                                                                                                                         \
            InputKeyEnum,                                                                                                                                                                                                                                                                                      \
            ParameterKeyEnum,                                                                                                                                                                                                                                                                                  \
            OutputKeyEnum,                                                                                                                                                                                                                                                                                     \
            InputTensorDimensionsPack,                                                                                                                                                                                                                                                                         \
            ParameterTensorDimensionsPack,                                                                                                                                                                                                                                                                     \
            OutputTensorDimensionsPack,                                                                                                                                                                                                                                                                        \
            TemplateParamTypesPack,                                                                                                                                                                                                                                                                            \
            TemplateParamNamesPack                                                                                                                                                                                                                                                                             \
        ),                                                                                                                                                                                                                                                                                                     \
        RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(InputKeyEnum))                                                                                                                                                                                                                                      \
    )                                                                                                                                                                                                                                                                                                          \
                                                                                                                                                                                                                                                                                                               \
    FOR_EACH_SEP5(                                                                                                                                                                                                                                                                                             \
        __IMPLEMENT_MODULE__IMPLEMENT_PARAM_BACKPROPAGATION_KERNEL,                                                                                                                                                                                                                                            \
        FORWARD(),                                                                                                                                                                                                                                                                                             \
        FORWARD(                                                                                                                                                                                                                                                                                               \
            ConcreteModuleName,                                                                                                                                                                                                                                                                                \
            ValueType,                                                                                                                                                                                                                                                                                         \
            InputKeyEnum,                                                                                                                                                                                                                                                                                      \
            ParameterKeyEnum,                                                                                                                                                                                                                                                                                  \
            OutputKeyEnum,                                                                                                                                                                                                                                                                                     \
            InputTensorDimensionsPack,                                                                                                                                                                                                                                                                         \
            ParameterTensorDimensionsPack,                                                                                                                                                                                                                                                                     \
            OutputTensorDimensionsPack,                                                                                                                                                                                                                                                                        \
            TemplateParamTypesPack,                                                                                                                                                                                                                                                                            \
            TemplateParamNamesPack                                                                                                                                                                                                                                                                             \
        ),                                                                                                                                                                                                                                                                                                     \
        RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(ParameterKeyEnum))                                                                                                                                                                                                                                  \
    )                                                                                                                                                                                                                                                                                                          \
                                                                                                                                                                                                                                                                                                               \
    TEMPLATE_MACROS__TEMPLATE_PREFIX(TemplateParamTypesPack, TemplateParamNamesPack)                                                                                                                                                                                                                           \
    HOST                                                                                                                                                                                                                                                                                                       \
    void                                                                                                                                                                                                                                                                                                       \
    TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(ConcreteModuleName, TemplateParamTypesPack, TemplateParamNamesPack)::backpropagate(AbstractTensorMap<ValueType>& costPartDerivWRTInput, AbstractTensorMap<ValueType>& costPartDerivWRTParameter, const AbstractTensorMap<ValueType>& costPartDerivWRTOutput) const \
    {                                                                                                                                                                                                                                                                                                          \
        __IMPLEMENT_MODULE__CHECK_COST_PART_DERIV_MAPS(                                                                                                                                                                                                                                                        \
            costPartDerivWRTInput,                                                                                                                                                                                                                                                                             \
            costPartDerivWRTParameter,                                                                                                                                                                                                                                                                         \
            costPartDerivWRTOutput,                                                                                                                                                                                                                                                                            \
            ConcreteModuleName,                                                                                                                                                                                                                                                                                \
            ValueType,                                                                                                                                                                                                                                                                                         \
            InputKeyEnum,                                                                                                                                                                                                                                                                                      \
            ParameterKeyEnum,                                                                                                                                                                                                                                                                                  \
            OutputKeyEnum,                                                                                                                                                                                                                                                                                     \
            InputTensorDimensionsPack,                                                                                                                                                                                                                                                                         \
            ParameterTensorDimensionsPack,                                                                                                                                                                                                                                                                     \
            OutputTensorDimensionsPack                                                                                                                                                                                                                                                                         \
        )                                                                                                                                                                                                                                                                                                      \
                                                                                                                                                                                                                                                                                                               \
        FOR_EACH_SEP5(                                                                                                                                                                                                                                                                                         \
            __IMPLEMENT_MODULE__CALL_INPUT_BACKPROPAGATION_KERNEL,                                                                                                                                                                                                                                             \
            FORWARD(),                                                                                                                                                                                                                                                                                         \
            FORWARD(                                                                                                                                                                                                                                                                                           \
                costPartDerivWRTInput,                                                                                                                                                                                                                                                                         \
                costPartDerivWRTOutput,                                                                                                                                                                                                                                                                        \
                ConcreteModuleName,                                                                                                                                                                                                                                                                            \
                ValueType,                                                                                                                                                                                                                                                                                     \
                InputKeyEnum,                                                                                                                                                                                                                                                                                  \
                ParameterKeyEnum,                                                                                                                                                                                                                                                                              \
                OutputKeyEnum,                                                                                                                                                                                                                                                                                 \
                InputTensorDimensionsPack,                                                                                                                                                                                                                                                                     \
                ParameterTensorDimensionsPack,                                                                                                                                                                                                                                                                 \
                OutputTensorDimensionsPack,                                                                                                                                                                                                                                                                    \
                TemplateParamTypesPack,                                                                                                                                                                                                                                                                        \
                TemplateParamNamesPack                                                                                                                                                                                                                                                                         \
            ),                                                                                                                                                                                                                                                                                                 \
            RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(InputKeyEnum))                                                                                                                                                                                                                                  \
        )                                                                                                                                                                                                                                                                                                      \
                                                                                                                                                                                                                                                                                                               \
        FOR_EACH_SEP5(                                                                                                                                                                                                                                                                                         \
            __IMPLEMENT_MODULE__CALL_PARAM_BACKPROPAGATION_KERNEL,                                                                                                                                                                                                                                             \
            FORWARD(),                                                                                                                                                                                                                                                                                         \
            FORWARD(                                                                                                                                                                                                                                                                                           \
                costPartDerivWRTParameter,                                                                                                                                                                                                                                                                     \
                costPartDerivWRTOutput,                                                                                                                                                                                                                                                                        \
                ConcreteModuleName,                                                                                                                                                                                                                                                                            \
                ValueType,                                                                                                                                                                                                                                                                                     \
                InputKeyEnum,                                                                                                                                                                                                                                                                                  \
                ParameterKeyEnum,                                                                                                                                                                                                                                                                              \
                OutputKeyEnum,                                                                                                                                                                                                                                                                                 \
                InputTensorDimensionsPack,                                                                                                                                                                                                                                                                     \
                ParameterTensorDimensionsPack,                                                                                                                                                                                                                                                                 \
                OutputTensorDimensionsPack,                                                                                                                                                                                                                                                                    \
                TemplateParamTypesPack,                                                                                                                                                                                                                                                                        \
                TemplateParamNamesPack                                                                                                                                                                                                                                                                         \
            ),                                                                                                                                                                                                                                                                                                 \
            RANGE(TENSOR_MAP_KEY_ENUM__INTERNAL_ENUM_NB_VALUES(ParameterKeyEnum))                                                                                                                                                                                                                              \
        )                                                                                                                                                                                                                                                                                                      \
    }

//////////////////////
// Main implementation

#define IMPLEMENT_MODULE(ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                            \
    TEMPLATE_MACROS__TEMPLATE_PREFIX(TemplateParamTypesPack, TemplateParamNamesPack)                                                                                                                                                                                                    \
    HOST                                                                                                                                                                                                                                                                                \
    TEMPLATE_MACROS__TEMPLATE_INSTANTIATION(ConcreteModuleName, TemplateParamTypesPack, TemplateParamNamesPack)::ConcreteModuleName(const RawTuple<FOR_EACH(__MODULE__TENSOR_INDEX_REF_PARAM, FORWARD(const), __MODULE__UNPACK(ParameterTensorDimensionsPack))>& parameterTensorsSizes) \
        : AbstractModule<                                                                                                                                                                                                                                                               \
            ValueType,                                                                                                                                                                                                                                                                  \
            InputKeyEnum,                                                                                                                                                                                                                                                               \
            ParameterKeyEnum,                                                                                                                                                                                                                                                           \
            OutputKeyEnum,                                                                                                                                                                                                                                                              \
            BuildTimeList::IntegerList<__MODULE__UNPACK(InputTensorDimensionsPack)>,                                                                                                                                                                                                    \
            BuildTimeList::IntegerList<__MODULE__UNPACK(ParameterTensorDimensionsPack)>,                                                                                                                                                                                                \
            BuildTimeList::IntegerList<__MODULE__UNPACK(OutputTensorDimensionsPack)>                                                                                                                                                                                                    \
        >(parameterTensorsSizes)                                                                                                                                                                                                                                                        \
    {}                                                                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                                                                        \
    __IMPLEMENT_MODULE__COMPUTE(ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                                     \
                                                                                                                                                                                                                                                                                        \
    __IMPLEMENT_MODULE__BACKPROPAGATE(ConcreteModuleName, ValueType, InputKeyEnum, ParameterKeyEnum, OutputKeyEnum, InputTensorDimensionsPack, ParameterTensorDimensionsPack, OutputTensorDimensionsPack, TemplateParamTypesPack, TemplateParamNamesPack)                               \
                                                                                                                                                                                                                                                                                        \
    IMPLEMENT_RTTI(ConcreteModuleName, Module<ValueType>, TemplateParamTypesPack, TemplateParamNamesPack)
